title: 'Ditto的小窝'
description: 'Web3.0时代的心理咨询师'
keyword: '但行好事,莫问前程'
url: "https://frankjason12138.github.io" # 主域名
baseurl: ""  # 你部署在 GitHub Pages 的根目录，所以为空

# 导航栏
nav:
  RSS: '/2025-01-01-RSS.html'
  心理测评: 'https://psych.dittoshop.cn/2025/04/01/Psychological-scale.html'
  港湾: '/'
  标签: '/tags.html'

# 作者
author: '木一'
nickname: 'Ditto'
bio: '但行好事 莫问前程'
avatar: '/assets/img/profile.png'

# 功能设置
search: true
nightMode: true
mathjax: true

# 评论
comments:
  disqus: true
  disqus_url: 'https://Ditto.disqus.com/embed.js'

# 分享
social-share: true
social-share-items: ['wechat', 'douban','weibo', 'twitter','facebook']

# 样式设置
theme-color: 'default'
postPatterns: 'seaOfClouds'

# 社交链接
sns:
  facebook: '//www.facebook.com/profile.php?id=100013380908553'
  zhihu: '//www.zhihu.com/people/Ditto12138'
  weibo: '//m.weibo.cn/profile/6045620905'
  github: '//github.com/FrankJason12138'

# 标签推荐
recommend-tags: true
recommend-condition-size: 12

# 分页
paginate: 6
paginate_path: 'page:num'

# 排除
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown 设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# 生成器插件（最终只写一次 plugins）
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# 固定链接结构
permalink: /:year/:month/:day/:title.html
